Move pypandoc.convert to pypandoc.convert_file
This should solve the error:

AttributeError: module 'pypandoc' has no attribute 'convert'

While installing with pip.

Signed-off-by: Jose Castillo <jcastillo@redhat.com>